// Downloads card images (full card + art crop) into images/ so the game runs offline,
// and writes js/images.js mapping card name -> local paths. Safe to re-run: existing files are skipped.
// Run: node tools/fetch-images.js
global.window = global;
const fs = require('fs');
const path = require('path');
require('../js/carddata.js'); require('../js/carddata-extra.js');
const root = path.join(__dirname, '..');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const slug = n => n.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

(async () => {
  const seen = new Set(), jobs = [], manifest = {};
  for (const c of window.CARD_DATA) {
    if (seen.has(c.name)) continue; // the game uses the first printing of each name
    seen.add(c.name);
    const s = slug(c.name);
    manifest[c.name] = {};
    if (c.img) { manifest[c.name].img = `images/cards/${s}.jpg`; jobs.push([c.img, manifest[c.name].img]); }
    if (c.art) { manifest[c.name].art = `images/art/${s}.jpg`; jobs.push([c.art, manifest[c.name].art]); }
  }
  fs.mkdirSync(path.join(root, 'images', 'cards'), { recursive: true });
  fs.mkdirSync(path.join(root, 'images', 'art'), { recursive: true });
  let done = 0, skipped = 0, failed = [];
  const worker = async () => {
    while (jobs.length) {
      const [url, rel] = jobs.shift();
      const file = path.join(root, rel);
      if (fs.existsSync(file) && fs.statSync(file).size > 1000) { skipped++; continue; }
      let ok = false;
      for (let attempt = 0; attempt < 3 && !ok; attempt++) {
        try {
          const r = await fetch(url, { headers: { 'User-Agent': 'UrzaMTGLocal/1.0' } });
          if (!r.ok) throw new Error('HTTP ' + r.status);
          fs.writeFileSync(file, Buffer.from(await r.arrayBuffer()));
          ok = true;
        } catch (e) { await sleep(1000 * (attempt + 1)); if (attempt === 2) failed.push(rel + ': ' + e.message); }
      }
      done++;
      if (done % 100 === 0) console.log(`${done} downloaded…`);
      await sleep(60);
    }
  };
  await Promise.all([worker(), worker(), worker(), worker()]);
  // only list files that exist so the game falls back to Scryfall for anything missing
  for (const name in manifest) for (const k of ['img', 'art']) if (manifest[name][k] && !fs.existsSync(path.join(root, manifest[name][k]))) delete manifest[name][k];
  fs.writeFileSync(path.join(root, 'js', 'images.js'), '// Generated by tools/fetch-images.js: local card images for offline play.\nwindow.CARD_IMAGES = ' + JSON.stringify(manifest) + ';\n');
  console.log(`done: ${done} downloaded, ${skipped} already present, ${failed.length} failed`);
  if (failed.length) console.log(failed.join('\n'));
})();
