// Downloads Urza's Saga / Legacy / Destiny card data from Scryfall (free public API)
// and writes js/carddata.js. Run: node tools/fetch-cards.js
const fs = require('fs');
const path = require('path');
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function main() {
  let url = 'https://api.scryfall.com/cards/search?q=' + encodeURIComponent('(e:usg or e:ulg or e:uds)') + '&unique=prints&order=set';
  const out = [];
  while (url) {
    const res = await fetch(url, { headers: { 'User-Agent': 'UrzaMTGLocal/1.0', Accept: 'application/json' } });
    if (!res.ok) throw new Error('HTTP ' + res.status + ' for ' + url);
    const j = await res.json();
    for (const c of j.data) {
      out.push({
        name: c.name,
        set: c.set,
        num: c.collector_number,
        cost: c.mana_cost || '',
        cmc: c.cmc,
        type: c.type_line,
        text: c.oracle_text || '',
        pt: c.power != null ? [c.power, c.toughness] : null,
        colors: c.colors || [],
        rarity: c.rarity,
        img: c.image_uris ? c.image_uris.normal : null,
        art: c.image_uris ? c.image_uris.art_crop : null,
      });
    }
    url = j.has_more ? j.next_page : null;
    await sleep(120);
  }
  const file = path.join(__dirname, '..', 'js', 'carddata.js');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, '// Generated by tools/fetch-cards.js from Scryfall. Do not edit.\nwindow.CARD_DATA = ' + JSON.stringify(out) + ';\n');
  console.log('wrote', out.length, 'printings');
}
main().catch(e => { console.error(e); process.exit(1); });
