// Downloads Tempest / Stronghold / Exodus card data from Scryfall (free public API)
// and writes js/carddata-tempest.js. Cards in CUT are left out on purpose (see README).
// Run: node tools/fetch-tempest.js
const fs = require('fs');
const path = require('path');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const CUT = require('./tempest-cut.js');

async function main() {
  let url = 'https://api.scryfall.com/cards/search?q=' + encodeURIComponent('(e:tmp or e:sth or e:exo) -t:basic') + '&unique=cards&order=set';
  const out = [], cut = [];
  while (url) {
    const res = await fetch(url, { headers: { 'User-Agent': 'UrzaMTGLocal/1.0', Accept: 'application/json' } });
    if (!res.ok) throw new Error('HTTP ' + res.status + ' for ' + url);
    const j = await res.json();
    for (const c of j.data) {
      if (CUT[c.name]) { cut.push(c.name); continue; }
      out.push({
        name: c.name, set: c.set, num: c.collector_number, cost: c.mana_cost || '', cmc: c.cmc, type: c.type_line, text: c.oracle_text || '',
        pt: c.power != null ? [c.power, c.toughness] : null, colors: c.colors || [], rarity: c.rarity,
        img: c.image_uris ? c.image_uris.normal : null, art: c.image_uris ? c.image_uris.art_crop : null,
      });
    }
    url = j.has_more ? j.next_page : null;
    await sleep(120);
  }
  const missing = Object.keys(CUT).filter(n => !cut.includes(n));
  if (missing.length) console.warn('CUT names not found in the sets:', missing);
  fs.writeFileSync(path.join(__dirname, '..', 'js', 'carddata-tempest.js'),
    '// Generated by tools/fetch-tempest.js from Scryfall. Do not edit.\nwindow.CARD_DATA = (window.CARD_DATA || []).concat(' + JSON.stringify(out) + ');\n');
  console.log('wrote', out.length, 'cards; cut', cut.length);
}
main().catch(e => { console.error(e); process.exit(1); });
