// Downloads non-Urza cards used by the spreadsheet decks into js/carddata-extra.js.
// Prefers the card's original-era printing. Run: node tools/fetch-extra.js
const fs = require('fs');
const path = require('path');
const EXTRA = ['Counterspell', 'Mind Over Matter', 'Fog', 'Respite', 'Verdant Force', 'Overrun', 'Eladamri, Lord of Leaves',
  'Kindle', 'Sonic Burst', 'Shock', 'Lightning Blast', 'Terror', 'Commander Greven il-Vec', 'Diabolic Edict', 'Dauthi Jackal',
  'Sorceress Queen', 'Vampiric Tutor'];
const SETS = ['tmp', 'sth', 'exo', 'vis', 'mir', 'wth', '5ed', '4ed'];
const sleep = ms => new Promise(r => setTimeout(r, ms));
const H = { headers: { 'User-Agent': 'UrzaMTGLocal/1.0', Accept: 'application/json' } };
(async () => {
  const out = [];
  for (const name of EXTRA) {
    // prefer Tempest block printings (the spreadsheet notes Tempest), then older core sets
    let c = null, r, j;
    for (const group of [['tmp', 'sth', 'exo'], SETS]) {
      const q = `!"${name}" (${group.map(s => 'e:' + s).join(' or ')})`;
      r = await fetch('https://api.scryfall.com/cards/search?unique=prints&order=released&dir=asc&q=' + encodeURIComponent(q), H);
      j = await r.json(); await sleep(120);
      c = j.data && j.data[0];
      if (c) break;
    }
    if (!c) { r = await fetch('https://api.scryfall.com/cards/named?exact=' + encodeURIComponent(name), H); c = await r.json(); }
    if (!c || !c.name) throw new Error('not found: ' + name);
    out.push({ name: c.name, set: c.set, num: c.collector_number, cost: c.mana_cost || '', cmc: c.cmc, type: c.type_line, text: c.oracle_text || '',
      pt: c.power != null ? [c.power, c.toughness] : null, colors: c.colors || [], rarity: c.rarity,
      img: c.image_uris ? c.image_uris.normal : null, art: c.image_uris ? c.image_uris.art_crop : null, extra: true, setName: c.set_name });
    console.log(c.name, '-', c.set_name);
    await sleep(120);
  }
  fs.writeFileSync(path.join(__dirname, '..', 'js', 'carddata-extra.js'), '// Generated by tools/fetch-extra.js from Scryfall. Do not edit.\nwindow.CARD_DATA = (window.CARD_DATA || []).concat(' + JSON.stringify(out) + ');\n');
  console.log('wrote', out.length);
})().catch(e => { console.error(e); process.exit(1); });
