# Builds pre-saved decks from magic.xlsx (one deck per sheet) into js/sheetdecks.js.
# Deck count per card = column B + column C (numeric values only). Rows without a count add 2 copies
# (once per card, even if the card is listed twice). Non-basic cards are capped at 4 copies (official rules).
# The sheet's basic land count is then adjusted so the deck is exactly 60. Run: python tools/import-sheet.py
import json, os, re, sys
import openpyxl

ROOT = os.path.join(os.path.dirname(__file__), '..')
BASIC = {'blue': 'Island', 'green': 'Forest', 'white': 'Plains', 'red': 'Mountain', 'black': 'Swamp'}
# changes requested on top of the spreadsheet (the basic land count is rebalanced to 60 afterwards)
ADJUST = {
    'green': {'Thorn Elemental': +1},
    'blue': {'Palinchron': +1, 'Archivist': +1, 'Somnophore': +1, 'Mind Over Matter': +1},
}
# spreadsheet spellings -> Oracle names
ALIASES = {
    'pacificism': 'Pacifism',
    'delusions of mastery': 'Delusions of Mediocrity',
    'eldamari lord of the leaves': 'Eladamri, Lord of Leaves',
    'commander greven-il-vec': 'Commander Greven il-Vec',
}

def known_names():
    names = set()
    for f in ('carddata.js', 'carddata-extra.js'):
        txt = open(os.path.join(ROOT, 'js', f), encoding='utf8').read()
        names.update(re.findall(r'"name":"((?:[^"\\]|\\.)*)"', txt))
    return {n.lower(): n for n in names}

def main():
    names = known_names()
    wb = openpyxl.load_workbook(os.path.join(ROOT, 'magic.xlsx'), data_only=True)
    decks, notes = {}, []
    for ws in wb.worksheets:
        counts, uncounted = {}, []
        for row in ws.iter_rows(values_only=True):
            raw = row[0]
            if not raw:
                continue
            n = sum(v for v in row[1:3] if isinstance(v, (int, float)))
            key = str(raw).strip().lower()
            name = names.get(ALIASES.get(key, key).lower())
            if not name:
                notes.append(f'{ws.title}: unknown card "{raw}" skipped')
                continue
            if n:
                counts[name] = counts.get(name, 0) + int(n)
            elif name not in uncounted:
                uncounted.append(name)
        for name in uncounted:
            if name not in counts:
                counts[name] = 2
                notes.append(f'{ws.title}: added 2 {name} (no count in sheet)')
        for name, n in ADJUST.get(ws.title.lower(), {}).items():
            counts[name] = counts.get(name, 0) + n
            notes.append(f'{ws.title}: {"+" if n > 0 else ""}{n} {name} (requested change)')
        basic = BASIC.get(ws.title.lower())
        for name, n in list(counts.items()):
            if n > 4 and name not in BASIC.values():
                notes.append(f'{ws.title}: {name} capped at 4 (sheet had {n})')
                counts[name] = 4
        total = sum(counts.values())
        if basic and total != 60:
            diff = 60 - total
            counts[basic] = counts.get(basic, 0) + diff
            notes.append(f'{ws.title}: {"added" if diff > 0 else "removed"} {abs(diff)} {basic} to make 60 ({counts[basic]} {basic} total)')
        cards = [name for name, n in counts.items() for _ in range(n)]
        decks[f'AC {ws.title.lower()}'] = cards
    out = '// Generated by tools/import-sheet.py from magic.xlsx. Do not edit.\n'
    out += 'window.MTG = window.MTG || {};\nwindow.MTG.SHEET_DECKS = ' + json.dumps(decks, indent=0) + ';\n'
    out += 'window.MTG.SHEET_NOTES = ' + json.dumps(notes) + ';\n'
    open(os.path.join(ROOT, 'js', 'sheetdecks.js'), 'w', encoding='utf8').write(out)
    for k, v in decks.items():
        print(k, len(v))
    print('\n'.join(notes))

main()
